name: Android Build APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          # 캐시 기능을 잠시 꺼서 클린 빌드를 유도합니다.
          
      # gradlew 파일에 문제가 있을 수 있으므로 
      # 시스템에 설치된 gradle을 사용하여 빌드합니다.
      - name: Build with Gradle
        run: gradle assembleDebug

      # 빌드된 APK 파일을 다운로드 가능하게 업로드
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: karatomo-debug-apk
          path: app/build/outputs/apk/debug/*.apk
